### ISSUE TITLE
As a developer, I can experiment with different model parameters

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/smartthings.htm.bridge#18]
There is currently only one set of model params used for every model. I want a way to destroy an existing model, replace it with a new model given a specific model params JSON string, then have all the existing data in InfluxDB for that sensor measurement get sent to the model until it catches up.

I don't want a web UI for all this stuff, I just need some command line tools to run these experiments that can connect to InfluxDB and HITC.

* * *

- [x] [Investigate cardinality in InfluxDB](https://github.com/nupic-community/smartthings.htm.bridge/issues/19)
- [x] [Update InfluxDB client to save into two measurements, one for HTM and one for raw data](https://github.com/nupic-community/smartthings.htm.bridge/issues/41)
- [x] [Create a cli script to delete a model and recreate with given model params](https://github.com/nupic-community/smartthings.htm.bridge/issues/20)
- [x] [HITC should handle batch data pushes](https://github.com/nupic-community/hitc/issues/26)
- [x] [Enable cli script to batch all existing data in InfluxDB into a model](https://github.com/nupic-community/smartthings.htm.bridge/issues/21)
